Add option to retrieve and pretty print a single file/URL.
- fixed spacing

diff --git a/tgebhardt/getbloblogs b/tgebhardt/getbloblogs
--- a/tgebhardt/getbloblogs
+++ b/tgebhardt/getbloblogs
@@ -1,21 +1,29 @@
 #!/usr/bin/env bash
 
 
-function show_usage {
-    echo "getbloblogs retrieves bloblogs for the given user between the times requested."
+function usage {
+    echo "getbloblogs retrieves and pretty prints bloblogs."
     echo
-    echo "Usage  : getbloblogs <user_id> <start_date> <end_date> [prod|staging|dev|smoke]"
-    echo "Example: getbloblogs 1055389923487515293 '2020-09-21 11:34:00' '2020-09-21 11:35:00' prod"
+    echo "Get logs for a user between two dates:"
+    echo "  Usage  : getbloblogs <user_id> <start_date> <end_date> [prod|staging|dev|smoke]"
+    echo "  Example: getbloblogs 1055389923487515293 '2020-09-21 11:34:00' '2020-09-21 11:35:00' prod"
     echo
-    echo "Usage  : getbloblogs <user_id> <hours_back> [prod|staging|dev|smoke]"
-    echo "Example: getbloblogs 1055389923487515293 3 staging"
+    echo "Get logs for a user going hours back:"
+    echo "  Usage  : getbloblogs <user_id> <hours_back> [prod|staging|dev|smoke]"
+    echo "  Example: getbloblogs 1055389923487515293 3 staging"
+    echo
+    echo "Get a specific bloblog via URL or locally:"
+    echo "  Usage  : getbloblogs <bloglog_url|local_file>"
+    echo "  Example: getbloblogs https://bloblogs.ops.lola.com/blobs/production/1522068005066900347/file.json"
     echo
     echo "If a bloblog has an embedded message, it will be extracted, pretty printed and "
     echo "saved to a new file with the same base name of the original file plus a message type"
     echo "and content type suffix. The orignal file is kept for context."
     echo
-    echo "For example, if the original file is named file.json and an XML message is detected"
-    echo "inside of it, then a new file called file.request.xml will be created."
+    echo "For example, if the original file is named file.json and an XML request is detected"
+    echo "inside of it, then a new file called file.request.xml will be created. The original file"
+    echo "is then renamed to file.json.orig. Metadata from the original is included in the newly formatted"
+    echo "file as a header comment to make grepping for things like search_id easier."
     echo
     echo "The <hours_back> parameter can be used to dynamically compute a time range"
     echo "from x hours ago until now."
@@ -24,6 +32,7 @@ function show_usage {
     echo "  brew install jq"
     echo "  brew install libxml2"
     echo
+    exit 1
 }
 
 function add_metadata {
@@ -39,17 +48,17 @@ function add_metadata {
     # if request_id wasn't found, try a variant where it is
     # called "id" nested in a "request" element
     if [[ $request_id == "null" ]]; then
-      request_id=$(jq -r ".request.id" $file)
+        request_id=$(jq -r ".request.id" $file)
     fi
     user_id=$(jq -r ".user_id" $file)
     timestamp=$(jq -r ".timestamp" $file)
 
     if [[ $comment_type == "xml" ]]; then
-      comment_block_start="<!--"
-      comment_block_end="-->"
+        comment_block_start="<!--"
+        comment_block_end="-->"
     else
-      comment_block_start="/*"
-      comment_block_end="*/"
+        comment_block_start="/*"
+        comment_block_end="*/"
     fi
 
     cat <<LOLA_HEADER
@@ -123,7 +132,6 @@ function format_sabre {
             jq -r ".${node}" $file | jq >> $json_msg_file
             found_body=1
         fi
-
     done
 
     # if we didn't find a json body then try looking for xml content
@@ -140,7 +148,7 @@ function format_sabre {
     fi
 
     if [ $found_body -eq 1 ]; then
-      mv $file $file.orig
+        mv $file $file.orig
     fi
 }
 
@@ -161,68 +169,102 @@ function format_file {
     fi
 }
 
+function aws_mfa_warning {
+    echo
+    echo "***** ERROR: aws s3 ls failed! Have you run aws-mfa recently?"
+    echo
+    exit 1
+}
 
+function process_file {
+    file=$1
+
+    # handles direct https linkd to blobs found in Sumo or Womcon
+    file=${file//https/s3}
+
+    # supports downloading from S3 or just formatting local files
+    if [[ $file == s3:* ]]; then
+        aws s3 cp $file . --quiet
+        if [ $? -ne 0 ]; then
+            aws_mfa_warning
+        fi
+        format_file `basename $file`
+    else
+        if [ ! -f $file ]; then
+           echo "***** ERROR: Local file not found"
+           echo $file
+           exit 1
+        fi
+        format_file $file
+    fi
+    exit 0
+}
+
+function process_by_time_range {
+    echo "Getting bloblogs for user ID $user_id between $start_date and $end_date using $env"
+    echo
+    echo "saving user's full bloblog list to /tmp/bloblogs.txt..."
+    # comment out this line once downloaded to speed up development/testing of this script
+    aws s3 ls $BLOBLOGS_BASE_URL/$user_id/ > /tmp/bloblogs.txt
+    if [ $? -ne 0 ]; then
+        aws_mfa_warning
+    fi
+
+    echo "downloading and processing bloblogs..."
+    cat /tmp/bloblogs.txt |
+    sort |
+    awk -F, "{ if (\$1>\"$start_date\" && \$1<\"$end_date\") print }" |
+    cut -c 32- |
+    while read -r line; do
+
+        # TODO: generalize provider filter
+        # if [[ $line != *Sabre* ]]; then
+        #   continue
+        # fi
+
+        echo "  $line"
+        aws s3 cp $BLOBLOGS_BASE_URL/$user_id/$line . --quiet
+        format_file $line
+    done
+}
 
 env="prod"
-if [ $# -eq 2 ]; then
+if [ $# -eq 1 ]; then
+    requested_file=$1
+elif [ $# -eq 2 ]; then
     hours_back=$2
     start_date=`date -v-${hours_back}H "+%Y-%m-%d% %H:%M:%S"`  # now - hours_back
     end_date=`date "+%Y-%m-%d% %H:%M:%S"`                      # now
 elif [ $# -eq 3 ]; then
     re='^[0-9]+$'
     if ! [[ $2 =~ $re ]] ; then
-      start_date=$2
-      end_date=$3
+        start_date=$2
+        end_date=$3
     else
-      hours_back=$2
-      start_date=`date -v-${hours_back}H "+%Y-%m-%d% %H:%M:%S"`  # now - hours_back
-      end_date=`date "+%Y-%m-%d% %H:%M:%S"`                      # now
-      env=$3
+        hours_back=$2
+        start_date=`date -v-${hours_back}H "+%Y-%m-%d% %H:%M:%S"`  # now - hours_back
+        end_date=`date "+%Y-%m-%d% %H:%M:%S"`                      # now
+        env=$3
     fi
 elif [ $# -eq 4 ]; then
     start_date=$2
     end_date=$3
     env=$4
 else
-    show_usage
-    exit 1
+    usage
 fi
 
 if [ $env == "prod" ]; then
-  BLOBLOGS_BASE_URL=s3://bloblogs.ops.lola.com/blobs/production
+    BLOBLOGS_BASE_URL=s3://bloblogs.ops.lola.com/blobs/production
 else
-  BLOBLOGS_BASE_URL=s3://bloblogs.ops.lola.co/blobs/$env
+    BLOBLOGS_BASE_URL=s3://bloblogs.ops.lola.co/blobs/$env
 fi
 
-user_id=$1
-
-
-echo "Getting bloblogs for user ID $user_id between $start_date and $end_date using $env"
-echo
-echo "saving user's full bloblog list to /tmp/bloblogs.txt..."
-# comment out this line once downloaded to speed up development/testing of this script
-aws s3 ls $BLOBLOGS_BASE_URL/$user_id/ > /tmp/bloblogs.txt
-
-if [ $? -ne 0 ]; then
-    echo
-    echo "***** ERROR: aws s3 ls failed! Have you run aws-mfa recently?"
-    echo
-    exit 1
+if [ -n $requested_file ]; then
+    process_file $requested_file
+else
+    user_id=$1
+    process_by_time_range
 fi
 
-echo "downloading and processing bloblogs..."
-cat /tmp/bloblogs.txt |
-sort |
-awk -F, "{ if (\$1>\"$start_date\" && \$1<\"$end_date\") print }" |
-cut -c 32- |
-while read -r line; do
 
-    # TODO: generalize provider filter
-    # if [[ $line != *Sabre* ]]; then
-    #   continue
-    # fi
-
-    echo "  $line"
-    aws s3 cp $BLOBLOGS_BASE_URL/$user_id/$line . --quiet
-    format_file $line
-done
